---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Generate SSL private key
  openssl_privatekey:
    path: "/etc/nginx/ssl_cert_key.pem"
    type: RSA 
    size: 2048
    state: present
  become: yes

- name: Generate self-signed SSL certificate
  openssl_certificate:
    path: "/etc/nginx/ssl_cert.crt"
    privatekey_path: "/etc/nginx/ssl_cert_key.pem"
    # privatekey_type: RSA 
    # bits: 2048
    provider: selfsigned
    state: present
  become: yes

- name: Copy config Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Nginx activate
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
  notify: Restart Nginx