---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Open SSL
  openssl_certificate:
    path: "/etc/nginx/{{ item.name }}"
    privatekey_path: "/etc/nginx/{{ item.name }}_key.pem"
    privatekey_type: rsa
    bits: 2048
    owner: root
    group: root
    mode: "0600"
  loop:
    - { name: "ssl_cert.crt" }
    - { name: "ssl_cert_key" }

- name: Copy config Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Nginx activate
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
  notify: Restart Nginx
